### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Requires https://github.com/conda-forge/databricks-cli-feedstock/pull/1 and https://github.com/conda-forge/staged-recipes/pull/8907

### CODE REVIEW

**Comment by jaroslawk** [comment]
@xhochy there is no gorilla dependency...

**Comment by xhochy** [comment]
@jaroslawk  `setup.py` lists it https://github.com/mlflow/mlflow/blob/3861af2c148a4259be969af12211aeb0e8815659/setup.py#L53 and the change introducing it is part of the 1.1.0 release

**Comment by xhochy** [comment]
@jaroslawk This is now ready for review/merge.

**Comment by jaroslawk** [comment]
@xhochy you are still faster than me to support this feedstock - Thank you for your contribution. 👍

**Pull request merged**
