### PR TITLE
MNT: rerender

### LINKED ISSUE #19: @conda-forge-admin please rerender
@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #19.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #19

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/help-python Any idea why conda-smithy only wants to build on Win?

**Comment by mariusvniekerk** [comment]
My guess is that the split package is being handled oddly

**Comment by xhochy** [comment]
I've copied the `conda-forge.yml` from a different repo and now it looks better.

**Comment by xhochy** [comment]
It's only building Python 3.7 now, Python 3.6 is missing...

**Comment by xhochy** [comment]
Many pitfalls with outputs, noarch & co here 😂

**Comment by mariusvniekerk** [comment]
Yeah, noarch + outputs + conda-smithy == a confused thing.

**Comment by xhochy** [comment]
Windows doesn't build as there is no `bld.bat`, taking care of that.

**Pull request merged**
