### PR TITLE
MNT: Added aarch64 and ppc64 support. Re-rendered with conda-build 3.19.1, conda-smithy 3.6.15, and co…

### PR DESCRIPTION
**Pull request by mgiessing**
…nda-forge-pinning 2020.03.24

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Shouldn't be there a change in `conda-forge.yml`?

@conda-forge-admin please rerender

**Comment by mgiessing** [comment]
I'm a bit confused - locally I added `provider: {linux_aarch64: default, linux_ppc64le: default}` to conda-forge.yml and rerendered with conda-smithy
Not sure why it didn't pushed or updated it in the github repo

**Comment by mgiessing** [comment]
@conda-forge-admin, please rerende

**Comment by mgiessing** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Thanks!

**Pull request merged**
